name: MobArena
version: 1.0
main: com.tonyb.mobarena.MobArena
author: Tonyb
description: A wave-based mob arena plugin

commands:
  spawnmob:
    description: Spawns a custom mob
    usage: /spawnmob
  startarena:
    description: Starts the arena fight